import { Transaction } from 'src/home/account-details/domain/transactions';

export const transactionsMocks: Transaction[] = [
  {
    id: 1,
    confirmedDate: new Date(2020, 11, 2, 14, 59),
    orderID: 'BXT7GU',
    orderCode: 'SETLMENT',
    transactionType: 'Paiment recived',
    debit: undefined,
    credit: 1,
    balance: 1,
  },
  {
    id: 2,
    confirmedDate: new Date(2020, 11, 2, 14, 58),
    orderID: 'BXT7GA',
    orderCode: 'SETLMENT',
    transactionType: 'Paiment recived',
    debit: undefined,
    credit: 1,
    balance: 1,
  },
  {
    id: 3,
    confirmedDate: new Date(2020, 11, 2, 14, 57),
    orderID: 'BXT7G9',
    orderCode: 'SETLMENT',
    transactionType: 'Paiment recived',
    debit: undefined,
    credit: 1,
    balance: 1,
  },
  {
    id: 4,
    confirmedDate: new Date(2020, 11, 2, 14, 56),
    orderID: 'BXT7G8',
    orderCode: 'SETLMENT',
    transactionType: 'Paiment recived',
    debit: undefined,
    credit: 1,
    balance: 33.37751972,
  },
  {
    id: 5,
    confirmedDate: new Date(2020, 11, 2, 14, 55),
    orderID: 'BXT7G7',
    orderCode: 'SETLMENT',
    transactionType: 'Paiment recived',
    debit: undefined,
    credit: 1,
    balance: 1,
  },
  {
    id: 6,
    confirmedDate: new Date(2020, 11, 2, 14, 54),
    orderID: 'BXT7G6',
    orderCode: 'SETLMENT',
    transactionType: 'Paiment recived',
    debit: undefined,
    credit: 1,
    balance: 1,
  },
  {
    id: 7,
    confirmedDate: new Date(2020, 11, 2, 14, 53),
    orderID: 'BXT7G6',
    orderCode: 'SETLMENT',
    transactionType: 'Paiment recived',
    debit: undefined,
    credit: 1,
    balance: 1,
  },
  {
    id: 8,
    confirmedDate: new Date(2020, 11, 2, 14, 52),
    orderID: 'BXT7G6',
    orderCode: 'SETLMENT',
    transactionType: 'Paiment recived',
    debit: undefined,
    credit: 1,
    balance: 1,
  },
  {
    id: 9,
    confirmedDate: new Date(2020, 11, 2, 14, 51),
    orderID: 'BXT7G6',
    orderCode: 'SETLMENT',
    transactionType: 'Paiment recived',
    debit: undefined,
    credit: 1,
    balance: 1,
  },
  {
    id: 10,
    confirmedDate: new Date(2020, 11, 2, 14, 50),
    orderID: 'BXT7G6',
    orderCode: 'SETLMENT',
    transactionType: 'Paiment recived',
    debit: 1,
    credit: 1,
    balance: 1,
  },
  {
    id: 11,
    confirmedDate: new Date(2020, 11, 2, 14, 49),
    orderID: 'BXT7G6',
    orderCode: 'SETLMENT',
    transactionType: 'Paiment recived',
    debit: 1,
    credit: 1,
    balance: 1,
  },
];
